### PR TITLE
Fix sdk e2e tests

### PR DESCRIPTION
**Pull request by sandeep-paliwal**
Added jwt key to generate token to travis yml and code to read the decrypted file and set env var

Fixed issue with build passing when tests have failed

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by shazron** [comment]
- analytics fixes depends on https://github.com/adobe/aio-lib-analytics/pull/39
- some state and tvm failures as well @moritzraho

**Comment by moritzraho** [comment]
@shazron @sandeep-paliwal failures for state and files are twofold:
a. `TypeError: Cannot read property 'newPipeline' of undefined` for files it seems there is a version mismatch for the azure sdk. I think it's worth trying to remove the package-lock and retry
b. `Request originated from client IP 34.66.178.120. This is blocked by your Cosmos DB account firewall settings.` now cosmos db is behind a FW and azure blob will soon be too (this week). So here we should either decide to run e2e tests from an allowed IP (internal, jenkins?) or build, deploy and run tests within a Runtime action with latest state and files changes.

For now I would suggest disabling the e2e tests for state and files and raise an issue. @meryllblanchet wdyt?

**Comment by meryllblanchet** [comment]
@moritzraho  Agreed!

**Comment by moritzraho** [comment]
removed tvm related tests  in https://github.com/adobe/aio-e2e-tests/pull/5, the master branch should be merged into this

**Comment by shazron** [comment]
@sandeep-paliwal analytics e2e failures "Unauthorized". Can you see what's up?

**Comment by sandeep-paliwal** [comment]
@shazron Built passed on re-run

**Pull request merged**
