### PR TITLE
enable audience manager tests

### LINKED ISSUE #27: Get Audience Manager env value
`AUDIENCE_MANAGER_ID` is missing for the tests (this is the "profile viewer id"). Right now the test is disabled in repositories.json

### PR DESCRIPTION
**Pull request by moritzraho**
## Description
resolves #27 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by moritzraho** [comment]
hmm e2e tests fail for campaign standard in node 10 anyone has an idea why?
cc @Himavanth @sandeep-paliwal @purplecabbage @rajarju @shazron @meryllblanchet

**Comment by shazron** [comment]
@moritzraho I got the same errors under node 10 but not node 12. Investigating

**Comment by shazron** [comment]
The Campaign tests are actually passing -- it's the test that behaves differently under node 10 vs 12 for this type of line: https://github.com/adobe/aio-lib-campaign-standard/blob/b059171b156866feceda79d52a253c679df801c3/e2e/e2e.js#L103

Fixing.

**Comment by shazron** [comment]
lib-campaign patched and released. I re-ran the PR jobs and everything passes except for Node 14 Windows - 3 analytics tests fail because of `Error: Too Many Requests`. So essentially I think all the tests are passing, but we need to figure out how to pace the tests so we don't get this error.

**Comment by moritzraho** [comment]
@shazron ok thanks for fixing the issue ! will merge

**Pull request merged**
